#!/usr/bin/env python3
"""
reason.py — the deterministic reasoning layer (typed-edge propagation).

Walks the Knowledge Graph's TYPED reasoning edges:
  - Market Context nodes carry `threatens:` / `strengthens:` (research-thesis links)
  - Research notes carry `invalidations:` (kill-switches) and `strengthens_when:`
  - Catalyst calendar (Important Dates) marks upcoming trigger points

It writes ~/Documents/Finance Knowledge Graph/Notes/<today> Reason.md —
an impact review: which theses the current regime threatens/strengthens, which
kill-switch invalidation conditions are live/at-risk, and upcoming catalyst
trigger points. This is layer 2; a graph-aware thesis-review skill interprets
it into a verdict (layer 3).

Usage:
    python3 reason.py                 # run against current market context
    python3 reason.py --catalyst      # also fold in upcoming catalysts (positions-monitor cron)
"""
import os, sys, glob, argparse, json
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kg_links  # noqa: E402

KG_NOTES = os.path.expanduser("~/Documents/Finance Knowledge Graph/Notes")
KG_ROOT = os.path.expanduser("~/Documents/Finance Knowledge Graph")


def _read_note_title(path):
    return os.path.splitext(os.path.basename(path))[0]


def load_context_nodes():
    ctx = {}
    for path in glob.glob(os.path.join(KG_ROOT, "Market Context", "*.md")):
        fm = kg_links.get_frontmatter(path)
        topic = fm.get("topic") or _read_note_title(path)
        ctx[topic] = {
            "regime": fm.get("regime"),
            "direction": fm.get("direction"),
            "threatens": fm.get("threatens", ""),
            "strengthens": fm.get("strengthens", ""),
            "last_updated": fm.get("last_updated"),
        }
    return ctx


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalyst", action="store_true")
    args = ap.parse_args()

    ctx = load_context_nodes()
    today = date.today().isoformat()

    # collect strengthens/threatens into per-thesis lists
    strengthens, threatens = {}, {}
    for topic, node in ctx.items():
        for t in _split_links(node.get("strengthens", "")):
            strengthens.setdefault(t, []).append(topic)
        for t in _split_links(node.get("threatens", "")):
            threatens.setdefault(t, []).append(topic)
    catalysts = kg_links.upcoming_catalysts(horizon_days=60) if args.catalyst else []

    _write_note(today, ctx, strengthens, threatens, catalysts, args.catalyst)


def _split_links(v):
    out = []
    for part in str(v).split(","):
        part = part.strip().strip("[]").strip('"')
        if part:
            out.append(part)
    return out


def _write_note(today, ctx, strengthens, threatens, catalysts, use_catalyst):
    import re
    os.makedirs(KG_NOTES, exist_ok=True)
    front = (
        "---\n"
        f'type: "research-note"\n'
        f'date: "{today}"\n'
        f'topic: "Reasoning — typed-edge regime/catalyst impact review"\n'
        'companies: []\n'
        'themes: [""]\n'
        'context: [""]\n'
        'sources: [""]\n'
        'status: "open"\n'
        'importance: 5\n'
        "---\n\n"
    )
    body = [f"# Reasoning Review {today}\n",
            "Auto-generated by reason.py — walks TYPED reasoning edges (threatens / strengthens / invalidation / catalysts).\n",
            "## Regime impacts on tracked theses\n"]
    for topic, node in ctx.items():
        body.append(f"### {topic}\n")
        body.append(f"Regime: **{node.get('regime') or '?'}** ({node.get('last_updated') or ''})")
        body.append(f"Direction: {node.get('direction') or '?'}\n")
        st = _split_links(node.get("strengthens", ""))
        th = _split_links(node.get("threatens", ""))
        body.append("**Strengthens these theses:**")
        if st:
            for t in st:
                body.append(f"- ✓ {t}")
        else:
            body.append("- (none)")
        body.append("**Threatens these theses (review for break):**")
        if th:
            for t in th:
                body.append(f"- ⚠ {t}")
        else:
            body.append("- (none)")
        body.append("")
    if use_catalyst and catalysts:
        body.append("## Upcoming catalysts (kill-switch trigger points)\n")
        body.append("| Date | Event | Company | Theses touched |\n|---|---|---|---|")
        for e in catalysts:
            body.append(f"| {e['date']} | {e['event']} | {e['company']} | {e.get('theses') or ''} |")
        body.append("\n- Each catalyst can CONFIRM or INVALIDATE the linked thesis — verify the kill-switch conditions at the trigger point.\n")
    body.append("## Kill-switch / invalidation conditions inventory\n")
    n_ks = 0
    for path in sorted(glob.glob(os.path.join(KG_NOTES, "*.md"))):
        fm = kg_links.get_frontmatter(path)
        inv = fm.get("invalidations", "")
        if inv:
            n_ks += 1
            body.append(f"- **{_read_note_title(path)}**: {inv}")
    if n_ks == 0:
        body.append("- (no invalidations tagged yet on research notes)")
    # dedupe lines
    seen = set(); final = []
    for line in body:
        key = line.strip()
        if key and key in seen and line.startswith("-"):
            continue
        if key:
            seen.add(key)
        final.append(line)
    title = os.path.join(KG_NOTES, f"{today} Reason.md")
    with open(title, "w", encoding="utf-8") as f:
        f.write(front + "\n".join(final) + "\n")
    print("wrote", title)
    print(f"context nodes: {list(ctx.keys())}")
    print(f"kill-switch-bearing notes: {n_ks}")
    if use_catalyst:
        print(f"upcoming catalysts: {len(catalysts)}")


if __name__ == "__main__":
    main()
